/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_practice;

import java.util.stream.IntStream;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String string = "this is a string";
        
        //streams
        IntStream
            .range(1,10)
            .forEach(System.out::print);
        System.out.println();
        
        string.chars().forEachOrdered(i -> System.out.print((char)i));
    }
}
